version: '3'
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
    network_mode: host
  app3:
    container_name: app3
    image: observabilitybreakdown/app3
    ports:
      - "8083:8083"
    network_mode: host
    build: ./app3
    depends_on:
      - jaeger
  app2:
    container_name: app2
    image: observabilitybreakdown/app2
    ports:
      - "8082:8082"
    network_mode: host
    build: ./app2
    depends_on:
      - app3
  app1:
    container_name: app1
    image: observabilitybreakdown/app1
    ports:
      - "8081:8081"
    network_mode: host
    build: ./app1
    depends_on:
      - app2