version: '3'
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
  app3:
    container_name: app3
    image: observabilitybreakdown/app3
    ports:
      - "8083:8083"
    build: ./app3
    depends_on:
      - jaeger
    environment:
      TRACING_COLLECTOR_HOST: ${TRACING_COLLECTOR_HOST}
  app2:
    container_name: app2
    image: observabilitybreakdown/app2
    ports:
      - "8082:8082"
    build: ./app2
    depends_on:
      - app3
    environment:
      TRACING_COLLECTOR_HOST: ${TRACING_COLLECTOR_HOST}
      EXCLUSIVE_TITLES_INTEGRATION_HOST: ${EXCLUSIVE_TITLES_INTEGRATION_HOST}
  app1:
    container_name: app1
    image: observabilitybreakdown/app1
    ports:
      - "8081:8081"
    build: ./app1
    depends_on:
      - app2
    environment:
      TRACING_COLLECTOR_HOST: ${TRACING_COLLECTOR_HOST}
      VENDORS_INTEGRATION_HOST: ${VENDORS_INTEGRATION_HOST}